#!/usr/bin/env node
/**
 * Static <head> + crawler files generator.
 *
 * WHY THIS EXISTS
 * This is a single-page app on static hosting. React fills in per-route metadata
 * at runtime (`src/lib/seo.ts`), which is enough for Google but not for the many
 * link unfurlers — chat apps, social previews, some crawlers — that read the HTML
 * they are served and never run JavaScript. So `index.html` ships a complete,
 * correct <head> for the home page, written from one source of truth.
 *
 * WHAT IT TOUCHES
 *   index.html            → the block between <!-- SEO:START --> and <!-- SEO:END -->
 *   public/robots.txt     → generated, gitignored from Prettier, safe to commit
 *   public/sitemap.xml    → every published route, including one entry per blog post
 *
 * Nothing else in the file is modified. Hand edits inside the marked block are
 * overwritten; edit src/config/site.config.json instead.
 *
 * Run it with `npm run seo`. It is wired to `prebuild`, so `npm run build` cannot
 * produce a bundle whose static head has drifted from the config.
 */

import { readFile, readdir, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import prettier from 'prettier'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const p = (...parts) => join(root, ...parts)

const START = '<!-- SEO:START'
const END = '<!-- SEO:END -->'

/** Fails the build with a readable message instead of a stack trace. */
function fail(message) {
  console.error(`\n[seo] ${message}\n`)
  process.exit(1)
}

/** Escapes a string for use inside an HTML attribute or text node. */
function esc(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

/** Joins the site origin and a path into one absolute URL, without double slashes. */
function absolute(siteUrl, path) {
  const origin = siteUrl.replace(/\/+$/, '')
  const suffix = path === '/' ? '/' : `/${path.replace(/^\/+/, '').replace(/\/+$/, '')}`
  return `${origin}${suffix}`
}

// ── Routes ───────────────────────────────────────────────────────────────────
// Read out of src/data/nav.ts rather than duplicated here, so a new page added to
// the navigation appears in the sitemap without anyone remembering to come back.
async function readNavRoutes() {
  const source = await readFile(p('src', 'data', 'nav.ts'), 'utf8')
  const routes = [...source.matchAll(/to:\s*'([^']+)'/g)].map((match) => match[1])
  if (routes.length === 0) fail('No routes found in src/data/nav.ts — has its shape changed?')
  return routes
}

// ── Blog posts ───────────────────────────────────────────────────────────────
// A second, deliberately minimal frontmatter reader. It cannot import the app's
// parser (that one is TypeScript, compiled by Vite), and it only needs two keys.
// If it and src/lib/blog.ts ever disagree, the app is authoritative — this one
// only decides what goes in the sitemap.
function frontmatterOf(source) {
  const match = /^---\r?\n([\s\S]*?)\r?\n---/.exec(source)
  if (!match) return null
  const fields = {}
  for (const line of match[1].split(/\r?\n/)) {
    const pair = /^([A-Za-z0-9_-]+)\s*:\s*(.*)$/.exec(line)
    if (pair) fields[pair[1]] = pair[2].trim().replace(/^['"]|['"]$/g, '')
  }
  return fields
}

async function readPosts() {
  let files
  try {
    files = await readdir(p('src', 'content', 'blog'))
  } catch {
    return [] // No blog directory yet: not an error.
  }

  const posts = []
  for (const file of files.filter((name) => name.endsWith('.md'))) {
    const source = await readFile(p('src', 'content', 'blog', file), 'utf8')
    const fields = frontmatterOf(source)
    const slug = file.replace(/\.md$/, '')

    if (!fields) {
      console.warn(`[seo] Skipping ${file}: no frontmatter block.`)
      continue
    }
    // Absent `published` means published — the app treats it the same way.
    if (fields.published === 'false') continue
    if (!/^\d{4}-\d{2}-\d{2}$/.test(fields.date ?? '')) {
      console.warn(`[seo] Skipping ${file}: date must be ISO, e.g. 2026-08-22.`)
      continue
    }
    posts.push({ slug, date: fields.date })
  }

  return posts.sort((a, b) => b.date.localeCompare(a.date) || a.slug.localeCompare(b.slug))
}

// ── index.html ───────────────────────────────────────────────────────────────
function buildSeoBlock(site) {
  const url = absolute(site.siteUrl, '/')
  const image = /^https?:\/\//i.test(site.ogImage)
    ? site.ogImage
    : absolute(site.siteUrl, site.ogImage)

  const lines = [
    `${START} — generated by scripts/generate-seo.mjs. Edit src/config/site.config.json instead; hand edits here are overwritten on build. -->`,
    `<title>${esc(site.title)}</title>`,
    `<meta name="description" content="${esc(site.description)}" />`,
    `<link rel="canonical" href="${esc(url)}" />`,
    `<meta name="author" content="${esc(site.name)}" />`,
    // One theme-color, no `media` attribute. See the long comment in index.html:
    // ThemeProvider overrides this imperatively, and `media` would outrank it.
    `<meta name="theme-color" content="${esc(site.themeColorDark)}" />`,
    `<meta property="og:type" content="website" />`,
    `<meta property="og:site_name" content="${esc(site.name)}" />`,
    `<meta property="og:locale" content="${esc(site.locale)}" />`,
    `<meta property="og:title" content="${esc(site.title)}" />`,
    `<meta property="og:description" content="${esc(site.description)}" />`,
    `<meta property="og:url" content="${esc(url)}" />`,
    `<meta property="og:image" content="${esc(image)}" />`,
    `<meta name="twitter:card" content="summary_large_image" />`,
  ]

  if (site.twitterHandle) {
    lines.push(`<meta name="twitter:site" content="${esc(site.twitterHandle)}" />`)
    lines.push(`<meta name="twitter:creator" content="${esc(site.twitterHandle)}" />`)
  }

  lines.push(
    `<meta name="twitter:title" content="${esc(site.title)}" />`,
    `<meta name="twitter:description" content="${esc(site.description)}" />`,
    `<meta name="twitter:image" content="${esc(image)}" />`,
    END,
  )

  return lines.join('\n    ')
}

/**
 * The pre-paint script in index.html hardcodes the two theme colours, because an
 * inline script cannot import JSON. This is the guard that keeps that copy honest:
 * if someone changes a colour in the config and not in the script, the build stops
 * here rather than shipping a page whose browser chrome flashes the wrong colour.
 */
function checkThemeColourDrift(html, site) {
  const problems = []
  if (!html.includes(`DARK = '${site.themeColorDark}'`)) {
    problems.push(`themeColorDark (${site.themeColorDark})`)
  }
  if (!html.includes(`LIGHT = '${site.themeColorLight}'`)) {
    problems.push(`themeColorLight (${site.themeColorLight})`)
  }
  if (problems.length > 0) {
    fail(
      `Theme colours in index.html's pre-paint script do not match site.config.json.\n` +
        `        Update the DARK/LIGHT constants in that inline script to: ${problems.join(', ')}`,
    )
  }
}

async function writeIndexHtml(site) {
  const file = p('index.html')
  const original = await readFile(file, 'utf8')

  const startAt = original.indexOf(START)
  const endAt = original.indexOf(END)
  if (startAt === -1 || endAt === -1 || endAt < startAt) {
    fail(`Could not find the ${START} … ${END} markers in index.html.`)
  }

  const next = original.slice(0, startAt) + buildSeoBlock(site) + original.slice(endAt + END.length)

  checkThemeColourDrift(next, site)

  // Formatted with the project's own Prettier config so `npm run format:check`
  // still passes on a freshly generated file. Without this, `npm run verify`
  // would fail on its own output.
  const config = await prettier.resolveConfig(file)
  const formatted = await prettier.format(next, { ...config, filepath: file })

  if (formatted === original) return false
  await writeFile(file, formatted, 'utf8')
  return true
}

// ── robots.txt ───────────────────────────────────────────────────────────────
async function writeRobots(site) {
  const body = [
    '# robots.txt — generated by scripts/generate-seo.mjs. Do not edit by hand.',
    '#',
    '# Note: crawlers only read /robots.txt at the host root. On a GitHub Pages',
    '# project deploy (…github.io/Portfolio/) this file is served from a sub-path',
    '# and is therefore ignored — which is fine, because that host is not the',
    '# canonical one. The canonical domain below is where it counts.',
    '',
    'User-agent: *',
    'Allow: /',
    '',
    `Sitemap: ${absolute(site.siteUrl, '/sitemap.xml')}`,
    '',
  ].join('\n')

  await writeFile(p('public', 'robots.txt'), body, 'utf8')
}

// ── sitemap.xml ──────────────────────────────────────────────────────────────
async function writeSitemap(site, routes, posts) {
  const entries = [
    ...routes.map((route) => ({ loc: absolute(site.siteUrl, route) })),
    ...posts.map((post) => ({
      loc: absolute(site.siteUrl, `/blog/${post.slug}`),
      lastmod: post.date,
    })),
  ]

  const body = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- Generated by scripts/generate-seo.mjs. Do not edit by hand. -->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    // No <priority> or <changefreq>: Google ignores both, and inventing a
    // change frequency for pages nobody has measured is a guess in a file that
    // reads as fact. <lastmod> appears only where a real date exists.
    ...entries.flatMap((entry) => [
      '  <url>',
      `    <loc>${esc(entry.loc)}</loc>`,
      ...(entry.lastmod ? [`    <lastmod>${entry.lastmod}</lastmod>`] : []),
      '  </url>',
    ]),
    '</urlset>',
    '',
  ].join('\n')

  await writeFile(p('public', 'sitemap.xml'), body, 'utf8')
  return entries.length
}

// ── main ─────────────────────────────────────────────────────────────────────
const site = JSON.parse(await readFile(p('src', 'config', 'site.config.json'), 'utf8'))

for (const key of ['name', 'title', 'description', 'siteUrl', 'ogImage', 'locale']) {
  if (!site[key]) fail(`site.config.json is missing a required key: "${key}".`)
}

const routes = await readNavRoutes()
const posts = await readPosts()

const htmlChanged = await writeIndexHtml(site)
await writeRobots(site)
const urlCount = await writeSitemap(site, routes, posts)

console.log(
  [
    '[seo] done',
    `      index.html        ${htmlChanged ? 'updated' : 'already current'}`,
    `      public/robots.txt written`,
    `      public/sitemap.xml written — ${urlCount} URLs (${routes.length} pages, ${posts.length} posts)`,
    `      canonical origin  ${site.siteUrl}`,
  ].join('\n'),
)
